on:
  push:
    branches:
      - "main"
    paths:
      - "wiki/**"
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          path: base-code
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          ref: master
          path: wiki-repo
      - name: Push to wiki
        run: base-code/scripts/sync-wiki.sh base-code wiki-repo
